version: '3.8'

services:
  reform-assistant:
    build: .
    ports:
      - "5000:5000"
    environment:
      - ANTHROPIC_API_KEY=${ANTHROPIC_API_KEY}
    restart: unless-stopped
    volumes:
      - ./src/database:/app/src/database

